---

- hosts: all
  become: true
  tasks:
    - name: install updates (AlmaLinux)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"