---

- hosts: all
  become: true
  tasks:
    - name: install updates (AlmaLinux)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install div (Ubuntu)
      tags: ubuntu,network-manager
      apt:
        name: network-manager
        state:  latest
      when: ansible_distribution == "Ubuntu"

    - name: install div (AlmaLinux)
      tags: editors
      dnf:
        name: tmux
        state: latest
      when: ansible_distribution == "AlmaLinux"