---

- hosts: workstations
  become: true
  tasks:
    - name: uninstall div (Ubuntu)
      tags: ubuntuws,tmux-uninstall
      apt:
        name: tmux
        state:  absent
      when: ansible_distribution == "Ubuntu"